spring:
  application:
    name: resource-server1
  zipkin:
    base-url: http://zipkin
  sleuth:
    sampler:
      percentage: 1.0
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
    resource:
      jwt:
        key-uri: http://localhost:8081/oauth/token_key

