version: '3'
services:
  db:
    image: fseebach/database:0.0.1-SNAPSHOT
    ports:
     - "5432:5432"
  eureka:
    image: fseebach/eureka-server:0.0.1-SNAPSHOT
    ports:
     - "8761:8761"
  rs1:
    image: fseebach/resource-server1:0.0.1-SNAPSHOT
    environment:
     - EUREKA_URI=http://eureka:8761/eureka
     - AUTH_SERVER_URI=http://auth-server:8081/
    restart: on-failure:5 
  frontend:
    image: fseebach/frontend:0.0.2-SNAPSHOT
    ports:
     - "80:80"
    environment:
     - EUREKA_URI=http://eureka:8761/eureka
  auth-server:
    image: fseebach/auth-server:0.0.1-SNAPSHOT
    ports:
     - "8080:8080"
    environment:
     - EUREKA_URI=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/login"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  gateway-server:
    image: fseebach/gateway:0.0.1-SNAPSHOT
    ports:
     - "8888:8888"
    environment:
     - EUREKA_URI=http://eureka:8761/eureka
     - AUTH_SERVER_URI=http://auth-server:8081/
#  zipkin-server:
#    image: demo/zipkin-server:0.0.1-SNAPSHOT
#    ports:
#     - "7777:7777"
#    environment:
#     - EUREKA_URI=http://eureka:8761/eureka
