CREATE USER auth WITH PASSWORD 'auth';
CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO auth;

CREATE USER rs1 WITH PASSWORD 'rs1';
CREATE DATABASE rs1;
GRANT ALL PRIVILEGES ON DATABASE rs1 TO rs1;